name: Upload Website

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy
        uses: reggionick/s3-deploy@v4
        with:
          folder: dist
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          bucket-region: ${{ secrets.AWS_S3_BUCKET_REGION }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: false
          files-to-include: '{.*/**,**}'